# Generated by Django 2.1.5 on 2019-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('real_name', models.CharField(max_length=20, verbose_name='真实名称')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录ip')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('create_time', models.DateTimeField(db_index=True, verbose_name='入库时间')),
                ('del_status', models.BooleanField(verbose_name='删除状态，1-删除， 0-未删除')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'backend',
            },
        ),
    ]
