# Generated by Django 2.1.5 on 2019-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='real_name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='真实名称'),
        ),
    ]
