# Generated by Django 2.1.5 on 2019-02-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0002_auto_20190228_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenu',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='update_time',
        ),
    ]
