# Generated by Django 2.1.5 on 2019-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0002_auto_20190118_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
    ]
