# Generated by Django 2.1.5 on 2019-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0003_auto_20190228_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=64, verbose_name='邮箱'),
        ),
    ]
