# Generated by Django 2.1.5 on 2019-01-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0003_auto_20190118_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='del_status',
            field=models.BooleanField(max_length=2, verbose_name='删除状态，1-删除， 0-未删除'),
        ),
    ]
