# Generated by Django 2.1.5 on 2019-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0004_auto_20190118_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='del_status',
            field=models.BooleanField(default=0, verbose_name='删除状态，1-删除， 0-未删除'),
        ),
    ]
