# Generated by Django 2.1.5 on 2019-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_django', '0007_auto_20190119_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='展示排序'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(max_length=64, null=True, verbose_name='菜单图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='父菜单ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(null=True, verbose_name='菜单URL'),
        ),
    ]
